baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Tangled Stories'
theme = 'paperesque'

[[params.topmenu]]
  name = "about"
  url = "about"

[[params.topmenu]]
  name = "rss"
  url = "posts/index.xml"
